base_images:
  operator-base:
    name: ubi
    namespace: ocp
    tag: "8"
binary_build_commands: make manager
build_root:
  from_repository: true
images:
- dockerfile_path: Dockerfile
  from: operator-base
  to: machine-deletion
releases:
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.10"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: make test
  container:
    from: src
- as: openshift-e2e
  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
  steps:
    workflow: optional-operators-ci-aws
    cluster_profile: aws
    env:
      OO_CHANNEL: alpha
      OO_INSTALL_NAMESPACE: mdr-install
      OO_PACKAGE: machine-deletion-remediation
      OO_TARGET_NAMESPACES: '!all'
    test:
    - as: e2e
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
zz_generated_metadata:
  branch: main
  org: medik8s
  repo: machine-deletion
